const LegalNotice = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-primary to-secondary py-12 px-4">
      <div className="max-w-4xl mx-auto bg-white rounded-3xl shadow-xl p-8">
        <h1 className="text-3xl font-bold mb-6">Condiciones Generales de uso</h1>
        <div className="prose max-w-none">
          <h2 className="text-xl font-semibold mt-6 mb-4">1. DEFINICIONES</h2>
          <p>«CGU»: se refiere a las presentes Condiciones Generales de Uso.</p>
          <p>«RECKON DIGITAL»: se refiere a la empresa RECKON DIGITAL , sociedad anónima simplificada, inscrita en el Registro Mercantil de París con el número 877 893 271, con domicilio social en 15, RUE DE LA PAROISSE, 78000 VERSAILLES (Francia); contacto: contact@leadstudio.fr; teléfono: [ADD].</p>
          <p>«Socio»: se refiere a cualquier entidad o entidades legales que proveen productos y/o servicios con los que los Usuarios se conectan usando el Servicio de Intermediación de Reckon Digital.</p>
          <p>«Servicio Complementario»: se refiere al (los) servicio(s) distinto(s) del Servicio de Intermediación, tal y como se especifica en el artículo 2 de las CDS.</p>
          <p>«Servicio de Intermediación»: se refiere al servicio de poner en contacto a los Usuarios con uno o varios Socios, tal y como se especifica en el artículo 2 de las CGU.</p>
          <p>«Servicio»: se refiere a los Servicios de Intermediación y Complementarios, considerados en su conjunto.</p>
          <p>«Sitio»: se refiere al sitio web leadstudio.com y a todas las páginas web desde las que los Servicios ofrecidos por Reckon Digital son accesibles a los Usuarios.</p>
          <p>«Usuario»: se refiere a cualquier persona física o jurídica que utilice cualquiera de los Servicios ofrecidos por Reckon Digital.</p>

          <h2 className="text-xl font-semibold mt-6 mb-4">2. ¿QUIENES SOMOS?</h2>
          <p>2.1. Reckon Digital es una empresa proveedora de servicios especializada en la intermediación del marketing digital. Reckon Digital ofrece a los usuarios: un Servicio de Intermediación, consistente en poner a los Usuarios, a petición expresa de éstos, en busca de productos y/o servicios, en contacto con Socios susceptibles de proporcionar los productos y/o servicios buscados; de forma ocasional, Servicios Adicionales al Servicio de Intermediación, como permitir que los Usuarios se pongan en contacto con otros Proveedores distintos a los que buscaban inicialmente, o que califiquen su experiencia con los Servicios de Reckon Digital.</p>
          <p>2.2. El Usuario accede a los Servicios haciendo clic en un contenido que se le ofrece. Sin embargo, Reckon Digital no se pone en contacto directamente con el Usuario para ofrecerle sus Servicios. Del mismo modo, en el contexto del Servicio de Intermediación: una vez realizada la conexión con un socio o socios, Reckon Digital: nunca se pone en contacto con el Usuario, y nunca interviene, de ninguna manera, en los intercambios entre ellos y todas las consecuencias que puedan resultar; no controla los métodos de contacto (teléfono, SMS, correo electrónico, etc.) por los que el/los socio/s se pondrá/n en contacto con el Usuario. Reckon Digital puede recibir una remuneración por determinados contratos que el Usuario pueda celebrar con uno o varios Socios con los que se haya puesto en contacto; en este caso, tenga en cuenta que Reckon Digital no interviene en la negociación y/o celebración y/o ejecución de los contratos así celebrados.</p>

          <h2 className="text-xl font-semibold mt-6 mb-4">3. OBJETO</h2>
          <p>3.1. El objetivo de estas condiciones de servicio es regular la relación entre Reckon Digital, por un lado, y los Usuarios, por otro, cuando navegan por el Sitio y/o utilizan los Servicios de Reckon Digital. En este sentido, estas condiciones de servicio constituyen el contrato entre Reckon Digital y los usuarios.</p>
          <p>3.2. El uso del Sitio y/o de los Servicios implica el consentimiento pleno y sin reservas del Cliente a estas CGU. Para ello, la Empresa invita al Cliente a leer atentamente las Condiciones de servicio. El Cliente declara y garantiza que ha leído y comprendido las CGU. Antes de utilizar los Servicios, se puede exigir al Usuario que acepte expresamente las CGU. En tal caso, el Usuario no podrá utilizar los Servicios si no acepta las CGU.</p>
          <p>3.3. Las CGU se complementan con la Política de Privacidad, que detalla la política de Reckon Digital en cuanto a la protección de los datos personales de los Usuarios durante la navegación por el Sitio y el uso de los Servicios, y la Política de Cookies, que informa a los Usuarios de las cookies utilizadas en el Sitio y de cómo gestionar su consentimiento para el uso de estas cookies.</p>

          <h2 className="text-xl font-semibold mt-6 mb-4">4. ACCESIBILIDAD A LOS SERVICIOS</h2>
          <p>4.1. Los Servicios son accesibles desde el Sitio. El acceso al Sitio requiere una conexión a Internet y un dispositivo que pueda navegar por Internet.</p>
          <p>4.2. Reckon Digital hará todo lo posible para mantener el Sitio accesible y funcionando sin demoras ni dificultades indebidas. Sin embargo, Reckon Digital no puede garantizar el acceso ininterrumpido al Sitio. En particular, Reckon Digital puede tener que llevar a cabo el mantenimiento y/o las actualizaciones de su Sitio, en particular para adaptar su contenido y/o integrar cambios en los Servicios. Además, Reckon Digital no puede garantizar el funcionamiento ininterrumpido de la red de Internet.</p>
          <p>4.3. Los usuarios son personalmente responsables de configurar y actualizar los recursos informáticos y de telecomunicaciones necesarios para acceder al Sitio. Todos los gastos relacionados corren a su cargo.</p>
          <p>4.4. Reckon Digital llama la atención de los usuarios sobre el hecho de que la red de Internet no es perfectamente segura. Por ello, Reckon Digital le recomienda que tome las medidas adecuadas para proteger sus datos, programas y dispositivos.</p>

          <h2 className="text-xl font-semibold mt-6 mb-4">5. ACCESIBILIDAD A LOS SERVICIOS</h2>
          <p>5.1. Para beneficiarse del Servicio de Intermediación y así ser puesto en contacto con uno o varios Socios, el Usuario debe: rellenar los campos señalados con un asterisco (*) o con una indicación de "campo obligatorio", hasta el final de la interfaz del sitio; los demás campos son opcionales; presentar la solicitud, siguiendo las instrucciones que aparecen en la pantalla al final de la interfaz del sitio.</p>
          <p>5.2. La solicitud de coincidencia puede no tener éxito si: el Usuario no completa el proceso de envío de la solicitud de emparejamiento; la información proporcionada, en particular los datos que permiten a los socios ponerse en contacto con los usuarios, es incorrecta.</p>
          <p>5.3. Cuando el Usuario del Servicio de Intermediación actúe como consumidor en el sentido de la Ley General para la Defensa de los Consumidores y Usuarios y la normativa aplicable en materia de consumidores, solicita la ejecución inmediata del contrato de intermediación con uno o varios Socios.</p>
          <p>5.4. Una vez que el usuario ha presentado una solicitud de coincidencia, Reckon Digital procesa la solicitud recibida. En ese momento, Reckon Digital puede ponerse en contacto con usted para confirmar la información proporcionada. Una vez que su solicitud es procesada y validada por Reckon Digital, su información es transferida a uno o más de los mencionados Socios dentro de las 24 horas siguientes a la validación de su solicitud.</p>
          <p>5.5. Ocasionalmente se ofrecen servicios adicionales a los usuarios, además del servicio de intermediación. Estos Servicios Adicionales son opcionales: los Usuarios nunca están obligados a utilizarlos para beneficiarse del Servicio de Intermediación.</p>

          <h2 className="text-xl font-semibold mt-6 mb-4">6. PRECIO</h2>
          <p>Los Servicios ofrecidos por Reckon Digital a los Usuarios son gratuitos, sin perjuicio de los costes de los recursos informáticos y de telecomunicaciones necesarios para acceder al Sitio.</p>

          <h2 className="text-xl font-semibold mt-6 mb-4">7. OBLIGACIONES DE LOS USUARIOS</h2>
          <p>7.1. En general, los Usuarios se comprometen a utilizar el Sitio y los Servicios de acuerdo con sus obligaciones legales y reglamentarias.</p>
          <p>7.2. En particular, los usuarios aceptan: no utilizar el Sitio y los Servicios con fines fraudulentos o malintencionados, y en particular con fines de perjuicio; no interrumpir voluntariamente el funcionamiento del Sitio y de los Servicios; no utilizar el Sitio y los Servicios con fines comerciales propios; no utilizar el Sitio y los Servicios apropiándose y/o usurpando la identidad de un tercero, ya sea natural o legal. No realizar cualesquiera otras actividades contrarias a la ley en vigor, las presentes Condiciones Generales de Uso o al orden público establecido, o con fines ilícitos, prohibidos o lesivos de derechos e intereses de Reckon Digital o de terceros.</p>
          <p>7.3. Cuando el Sitio incluye campos libres, los Usuarios garantizan que la información introducida: no contenga declaraciones falsas, denigrantes, difamatorias, de odio o de apología del odio y/o de acoso ilegal a cualquier persona jurídica y/o física, de acuerdo con la normativa aplicable; no atenten contra la intimidad o la imagen de terceros, incluidos los derechos de las personas físicas respecto a sus datos personales, de acuerdo con el Reglamento nº 2016/679, de 27 de abril de 2016, relativo a la protección de las personas físicas en lo que respecta al tratamiento de datos personales y a la libre circulación de estos datos y el resto de normativa aplicable en este contexto.</p>
          <p>7.4. Los Usuarios serán los únicos responsables frente a Reckon Digital y frente a terceros de cualquier daño o perjuicio que pudiera causarse como consecuencia del incumplimiento de las obligaciones previstas en estas Condiciones Generales de Uso.</p>

          <h2 className="text-xl font-semibold mt-6 mb-4">8. PROPIEDAD INTELECTUAL E IMAGEN</h2>
          <p>8.1. El Sitio, ya sea en su conjunto o en sus componentes individuales, cualesquiera que sean (en particular los textos, las ilustraciones, las fotografías, las marcas, los diseños, las denominaciones, los logotipos, los productos, los programas informáticos, los códigos fuente o cualquier elemento gráfico, sonoro, interactivo, de vídeo o multimedia, etc.), están protegidos por los derechos de propiedad intelectual. Estos derechos son propiedad exclusiva de Reckon Digital, sus socios y/o terceros. Por lo tanto, cualquier uso de estos elementos (incluyendo la reproducción, comunicación, la puesta a disposición, la distribución, la transformación o la modificación, etc.), en su totalidad o en parte, requiere el consentimiento previo por escrito de Reckon Digital y/o de su propietario, excepto cuando lo permita la ley.</p>
          <p>8.2. El Sitio también es susceptible de contener elementos, cualesquiera que sean (incluida la imagen, la voz, etc.), que representen total o parcialmente la imagen de una persona física. Por lo tanto, cualquier uso de estos elementos (incluyendo la reproducción, comunicación, descarga, modificación, traducción, etc.), en su totalidad o en parte, requiere el consentimiento previo por escrito de Reckon Digital y/o de la persona interesada, excepto cuando lo permita la ley.</p>
          <p>8.3. Estas CGU y toda la documentación legal de Reckon Digital son propiedad exclusiva de Reckon Digital. Está estrictamente prohibido reproducir o imitar, total o parcialmente, cualquiera de estos elementos sin el consentimiento previo por escrito de Reckon Digital.</p>

          <h2 className="text-xl font-semibold mt-6 mb-4">9. RESPONSABILIDAD</h2>
          <p>9.1. Reckon Digital hace sus mejores esfuerzos para mantener los Servicios operativos y accesibles sin demoras ni dificultades indebidas para los Usuarios. Reckon Digital tiene una obligación de medios, salvo que la ley disponga lo contrario.</p>
          <p>9.2 Cuando el Usuario es un consumidor tal y como se define en el artículo primero del Código de Consumo francés, Reckon Digital no se hace responsable de los daños causados por el incumplimiento parcial o total de las presentes CGU cuando el incumplimiento sea consecuencia de: la culpa y/o el incumplimiento por parte del usuario de las obligaciones que se le atribuyen en virtud de las presentes CGU que causen un daño o perjuicio a Reckon Digital; el acto imprevisible e insuperable de un tercero; un acontecimiento de fuerza mayor.</p>
          <p>9.3. Cuando el Usuario actúa como profesional, la responsabilidad de Reckon Digital hacia los Usuarios se limita a los daños materiales directos causados por el incumplimiento, parcial o total, de las presentes CGU, con exclusión de cualquier otro daño.</p>
          <p>9.4. Reckon Digital no se responsabiliza de los litigios que puedan surgir entre un Usuario y el o los Socios con los que se haya puesto en contacto, siendo Reckon Digital un tercero en las relaciones que puedan surgir entre estos últimos, sea cual sea la causa.</p>
          <p>9.5. Se pueden insertar hipervínculos en el Sitio y dirigir a los Usuarios a sitios web que son terceros de Reckon Digital. Reckon Digital llama la atención del Usuario sobre el hecho de que no tiene ningún control sobre estos sitios web. En consecuencia, el Usuario reconoce que Reckon Digital no es responsable de la exactitud de sus contenidos, ni de su adecuación a la legislación aplicable.</p>

          <h2 className="text-xl font-semibold mt-6 mb-4">10. CAMBIOS Y ACTUALIZACIONES</h2>
          <p>10.1. Reckon Digital se reserva el derecho de modificar sus CGU en cualquier momento para adaptarlas a la evolución del Sitio, los servicios y/o la legislación.</p>
          <p>10.2. Las nuevas disposiciones de las condiciones de servicio sólo serán aplicables a los usuarios desde el momento en que se publiquen en el sitio. Si la ley lo exige, se les comunicarán previamente las CGU actualizadas y/o se les invitará a aceptarlas expresamente con anterioridad. En este último caso, los Usuarios que no acepten las condiciones de servicio modificadas no podrán utilizar los Servicios.</p>

          <h2 className="text-xl font-semibold mt-6 mb-4">11. VARIOS</h2>
          <p>11.1. En el caso de que una de las disposiciones de las CGU se considere nula, sin efecto o no escrita en virtud de una disposición legal o reglamentaria o de una decisión judicial con fuerza de cosa juzgada, las demás disposiciones seguirán en vigor.</p>
          <p>11.2. El hecho de no acogerse a alguna de las disposiciones de las CGU no se interpretará como una renuncia al derecho de acogerse a dicha disposición con posterioridad.</p>

          <h2 className="text-xl font-semibold mt-6 mb-4">12. LEY Y JURISDICCIÓN APLICABLE</h2>
          <p>12.1. Las CGU se rigen por la legislación que corresponda de acuerdo con la Ley General para la Defensa de los Consumidores y Usuarios y la normativa aplicable en materia de consumidores, o, en su defecto por la legislación francesa Cualquier controversia que pueda surgir con relación a la presente relación contractual se someterá a los tribunales que correspondan de acuerdo con la Ley General para la Defensa de los Consumidores y Usuarios y la normativa aplicable en materia de consumidores, o, en su defecto, a los tribunales competentes de la ciudad de Paris (Francia).</p>
          <p>12.2. Cuando el Usuario es un consumidor tal y como se define en el artículo preliminar del Código de Consumo francés, en caso de litigio relacionado con la ejecución de las CGU: Las controversias relativas a las presentes CGU se someterán a los tribunales competentes del lugar de residencia del Usuario; Además, el Usuario tiene la posibilidad, antes de emprender cualquier acción legal, de recurrir a una solución amistosa y, en particular, a un procedimiento de mediación convencional o a cualquier otro método alternativo de resolución de conflictos ("ADR"). El listado de plataformas ADR disponibles de la Comisión Europea puede consultarse en el siguiente enlace: https://webgate.ec.europa.eu/odr/main/index.cfm?event=main.home.chooseLanguage. Desde esta plataforma, las partes pueden presentar una reclamación en línea contra la otra, que será informada de ello.</p>
          <p>12.3. Cuando el Usuario actúe como profesional, los tribunales de la jurisdicción del Tribunal de Apelación de París serán los únicos competentes para conocer cualquier litigio que surja con Reckon Digital en relación con la interpretación, la validez y/o la ejecución de las CGU y, más generalmente, con sus relaciones contractuales y comerciales y sus consecuencias.</p>
          <p>12.4. Si el Usuario, independientemente de su estatus, reside o está establecido en un país distinto de Francia, no se verá privado de las disposiciones de orden público de la ley del país en cuestión, que son irrenunciables.</p>

          <h2 className="text-xl font-semibold mt-6 mb-4">13. Cookies</h2>
          <p>Encontrará la información relevante sobre las Cookies que utilizamos aquí.</p>

          <h2 className="text-xl font-semibold mt-6 mb-4">14. Datos personales</h2>
          <p>Encontrará la información relevante sobre los datos personales que recopilamos aquí.</p>

          <p className="mt-8 text-sm text-gray-600">Fecha de actualización: 03/12/2024</p>

          <p className="mt-8 font-semibold">Luz y gas, la oferta que se adapte mejor a ti.</p>
        </div>
      </div>
    </div>
  );
};

export default LegalNotice;